# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mangoblog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Pi=3.1415926
  servlet: #文件上传相关
    multipart:
      #enabled: true #配置文件传输协议，都是使用默认值
      #file-size-threshold: 0 #配置文件传输协议，都是使用默认值
      max-request-size: 100MB #设置单个请求大小
      max-file-size: 100MB #设置总数据大小
  elasticsearch:
    uris: 127.0.0.1:9200
  logging:
    level:
      root: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.mango.mangoblog.entity.User  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl